services:
  postal:
    build:
      context: .   # Uses the Dockerfile in your repo
    entrypoint: ["/docker-entrypoint.sh"]
    volumes:
      - "./docker/ci-config:/config"
    env_file: .env  # Load environment variables from the .env file
    environment:
      POSTAL_SIGNING_KEY_PATH: /config/signing.key
      LOGGING_ENABLED: "false"
      RAILS_ENVIRONMENT: test
      RAILS_LOG_ENABLED: "false"
      WAIT_FOR_TIMEOUT: 90